### ISSUE TITLE
loading on the same version fails with "too old" ERROR

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1167]
This may be a duplicate.
The following score returns this error on load.

[FUSION-BRANDNEW-114.zip](https://github.com/ossia/score/files/6237219/FUSION-BRANDNEW-114.zip)

**Comment by jcelerier** [comment]
yep it's the issue we fixed yesterday because of the NaNs... it won't do that anymore with the next release

**Comment by thibaudk** [comment]
aa cool, didn't realize they where related.

**Comment by thibaudk** [comment]
Maybe the fix will prevent saving a faulty scenario, but after a fresh pull and rebuild, it still doesn't seem to allow loading this particular score.

**Comment by jcelerier** [comment]
yes it has to be fixed by hand, I did it and sent it to its author

**Comment by thibaudk** [comment]
verry nice !

**Comment by thibaudk** [comment]
this happened again with the latest a35 release.
from a blank scenario, adding an osc Device, a few sound files and one automation.
reloading it fails with the same message
