### ISSUE TITLE
crash when editing a device

### ISSUE THREAD

**Issue by avilleret** [ossia/score#68]
with 0a135f4 : 
1. open i-score
2. add a new (minuit or OSC) device
3. right click on it > edit 
4. click OK in the properties window
kaboum !

Here is the backtrace : https://gist.github.com/avilleret/e1ef69d61f2db67fed8b

**Comment by theod** [comment]
I assign to jcelerier as he has made some changes recently on this part.

**Comment by theod** [comment]
I can experience the same crash on my side.
here is a screenshot of what happens in Xcode : 

![capture d ecran 2015-11-09 a 14 39 27](https://cloud.githubusercontent.com/assets/118426/11035004/d00ff4f0-86ef-11e5-84e6-16c8aa47b54a.png)

**Comment by jcelerier** [comment]
I've done some work but there might be remaining corner cases, please test

**Comment by theod** [comment]
I had another crash.
the tree was unfold and I've made an automation and played it.

![capture d ecran 2015-11-09 a 19 26 14](https://cloud.githubusercontent.com/assets/118426/11042554/10c2a3bc-8718-11e5-952f-31e635a350bd.png)

**Comment by jcelerier** [comment]
Should be fixed in 88b938d

**Comment by theod** [comment]
I tried but I still have the same problem.
I try to edit the device after playing around with i-score (I create an automation, I play it, ... then I try to edit the device).

here is a crash log : 

[crashlog - device edit.txt](https://github.com/OSSIA/i-score/files/30707/crashlog.-.device.edit.txt)

**Comment by jcelerier** [comment]
eh... I think that this should be completely forbidden because when the
settings are updated the device is removed and recreated afterwards.

**Comment by theod** [comment]
ouch ! I'm pretty sure this will be a problem for users !
I ask to @bltzr, @reno- and @jln-

**Comment by reno-** [comment]
of course it could be useful to edit the device, for exemple if we need to change UDP ports.
Maybe the project might be automagiccally closed and re-open to avoid crash?

**Comment by theod** [comment]
it sounds like an API network design issue so I propose to postpone this issue for the 1.1 version as I need to rewrite this part. maybe we could just lock the Edit access for a while ?

**Comment by avilleret** [comment]
I need to edit device _after_ creating come contents.
for example, if my device's IP changed for any reason or if I need to change port settings (because port could be blocked after a software crash)

**Comment by jcelerier** [comment]
To be clear, the problem is absolutely not editing a device after editing content, it is editing the parameters of a device _while the score is executing_.

**Comment by theod** [comment]
no ! je continue en céfran parce qu'on s'embrouille pour rien là ! je disais que j'avais essayé d'éditer le device après avoir créer puis joué une automation (pas pendant) !

**Comment by jcelerier** [comment]
ahh XD d'accord. Bon ça me fait moins peur alors. Je suis dessus là...

**Comment by jcelerier** [comment]
Please test 9a70e6ed67eea39916a5e1501a924a5e9ea01a67

**Comment by theod** [comment]
this is fixed ! thanks !
