### ISSUE TITLE
notify of the creation of an object after its name has been changed 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#682]
currently, this happens before it's changed, which causes confusion when remotely observing score's namespace/structure

another option would be to add a notification to OSCquery when an object is renamed (because we'll have the same problem if somebody renames an object during its lifespan)

what do you think @jcelerier ?

**Comment by jcelerier** [comment]
> another option would be to add a notification to OSCquery when an object is renamed

they do exist actually, not sure why it's not working

**Comment by bltzr** [comment]
that’s supposed to be PATH_CHANGED right ?

**Comment by bltzr** [comment]
maybe we just didn't put this into ossia-Max/pd specifications ? (again)

**Comment by bltzr** [comment]
this can be tested with https://github.com/OSSIA/score/blob/master/Documentation/Examples/Max/score-client.maxpat
- create a local device in score
- connect in Max
- create objects in score
- see notifications in the Max window
-> they don't have the right name

**Comment by bltzr** [comment]
after some further testings, it seems that actually notifying the name change (with PATH_CHANGED ?) could be a better, more generic (because it would also help when the user actually changes an object name manually) way to solve this problem.

another way to see the problem is to use the attached score - there are two devices:
- 'score' is the local device
- 'score-remote' is the same one, but observed through oscquery
as one can notice, when adding e.g. intervals (that's the same with syncs/states/events), the names are not updated
one needs to refresh the namespace in order to get the correct names

**Comment by bltzr** [comment]
as a side note, this creates an annoying behavior in ossia-max/pd (and then I guess in all other flavors of libossia...): when asking the remote device for its namespace, the reply takes ages to come because, for every object that has been rename ossia-* will ask for the values of all its attributes and will wait 3 seconds each time before giving up and trying with the next one

**Comment by bltzr** [comment]
forgot the .score attachment
[testObjectNames.score.zip](https://github.com/OSSIA/score/files/1491867/testObjectNames.score.zip)

also, you'll have to unfold the DE's tree down to this to actually notice the problem
![tree](https://user-images.githubusercontent.com/113982/33080084-82f9fefe-ced7-11e7-844a-abd1e0d308a1.png)

**Comment by jcelerier** [comment]
should be fixed now

**Comment by bltzr** [comment]
sorry, it's not fixed (with 2.0a4), one needs to refresh the namespace (when opening the local device as an oscquery device) in order to see the new intervals appear with the correct name

![intervalnames](https://user-images.githubusercontent.com/113982/41500777-62ee2450-7198-11e8-8f5d-68151d139bf2.gif)

**Comment by bltzr** [comment]
![refresh](https://user-images.githubusercontent.com/113982/41500797-9eb4eaf0-7198-11e8-953c-2d60eb064722.gif)

**Comment by jcelerier** [comment]
is it still the case ?

**Comment by jcelerier** [comment]
bump

**Comment by avilleret** [comment]
PATH_RENAMED handling have been revamped with https://github.com/OSSIA/libossia/commit/0d8baace18223b6085656a23ee57ab505e78f764
maybe it's worth a try

**Comment by jcelerier** [comment]
closing, please reopen if it's still buggy but I'm pretty sure it works nowadays

**Comment by bltzr** [comment]
yes I confirm it does work in Score

**Comment by bltzr** [comment]
there's still something wrong here:

the node is renamed, but not its children (nodes &) parameters,
this can be reproduced with the patcher below:
<pre><code>
----------begin_max5_patcher----------
1692.3oc2YtziaaCD.9r2eEr5Ra.7ZKQIYYkCEHG5gbnnG1ioEFzRz1LqLo.
I8tdaP9uW9PxVR1RwV9QVzbXgyPQxgeb3vYF9sGF3LmsEKb.eD7EvfAe6gAC
LhzBFT7+G3rFsMICILelSBa8ZLU5Lz1lDuUZjSYuBjqv.J9U.gJw7WPY.JZM
FPD.I5YLUKlAPIIrMTI3uo+FhlZ6xl0ywbb599kxvB5uJAux3OCPz2.qYb7P
vqqHIqzi2RFK8CkpPFghMioVOfEBUiIaiLCKMZsagzbjLYEgtbFGmHsqZuvn
QtCAAtQil54FFDMD3OwSKx2ejK3eJ5II0rJYy+5iPem8SBgVNGdkyAGKT.BI
ILZ04Yhay4wHvsxjHjukgMyiiVv2e3A8eFdg6LBzKXfl0bbFCYQtHQATmdxJ
+n3cqAXPnVDzsEVA6EqhmZYUv8lUO96.hrl42ub1TB5Yzd+ffSlRt8gRvPyf
5O4taQkvxeyXF03fN0HDklpTXAXtxb60dPOygOXr2oROu3dQufXC87tYzSxV
tLqkCYdsCf.q4i2jvJ.vr9CpnZ1wR9VN11KGh1+2wnyTmcyEWsKo1vlgon41
ElaOHWP3DiBFWxq6gImbkxsuXEaSVp4X4466ZpuAhd96wJzqS6pI8x20TnYP
8g26Sk5afS3XjTcDr90vK3r0V29RDWNT+SJHOC814SQeeqwYka.hlzIEC6EE
8s1XQSu2TTiE8c.+FZIhPGBdBs9CmMlr20GZYkWPm7InO7IvfGabJWYvnrbT
50gbAzp8RGNyfSadnytwBgc4K63Nx5NrqJK5ppClWrTKVqCbVPxvuf4BEPqz
+ANn77JhGToKZ.8UlYfhFtSDgZE4uSDG+Bor+g6jh3JnHUDYC2peamTtkqGF
VJlS2PLphUnZq5gxArji6c0NIvFG4zJ63pszkYrjmwoUrKUbMGSIzpVP0ZNE
u.sISNaAiJEj+0nbdZmWGo8EnDbqcVe4uYk8INAkUt1bVxIoLpVIpwYs3xoS
GRo4LRX0Ei4Knn7izYkgfhIsznx6lbiXNhq2FJtfCV1njwxp2zt9kgWHKZNm
PoMnnjk2dibxxUcz24LUiq6ZrMsHlsgZacl5XnblNh85eGJKq3bY8geKhRVq
73KI1s.n6tFsWxuRjvYYY0Vu1Vd4HsjprfSvuRRkqLSTUiA0mSxKMhb1sKmR
VhEx5xjnkh5RN3zoRzl4EmPmIwqUtckM9fZolV83XUOX0j2kmrFgS.H.R0Vp
6QCVoki3UKzbDzy00Fo5nv5NzZO.sg0iS6.WbtMToCbycL+6CJ8wW3735SKA
NC31aZEYuFLLXj2z3fP+icGvwQ1bDcolYsBr3V4E7mIuTtbU9lRAiEJmGsyM
uSgaPeyUnEQu9CQVqnZ56SSqcnpR3nmOprGHgtQWETE8SDUl45B4fMBA+c+8
G6WpUGRdshB2iihJRKivtobBMEusR7NWEtYWVsCN2e.3B0Nw8gcQtpbAdtlH
WJW1GcjtbmsbsnYgoa+3.Sv1vSJ21KbeBpuFUWyKIzcwJ9kc9Nze2Iscct5f
9NOf2InDQ2Zk3THQ7sTI7NQknTauIZQzopDvanRL8xUhBgkISYpBd5La9CyP
RImLeizdPpZ1gmUbtpjtlixJhhcWVPcEz69HieXu9depqnMUbaMItjBJB85c
AEugkFjQwl5BJ56iZD6tqDESi5pfM8qpf1bElFdGKYpN+XfJ6zbwGGOdIQtZ
y7Qpuc7e8zSe9SiMu.ziaDX9iYj4bD+swyUlyiWqR.EyG+jtYw3+XKRkZl5G
+IZ6X0wE4n98xQViOao8C85rfggN2NSnEYL0ndbsG1gIRgFWoLVEQb1cYrFV
jByQOFUpEKXbUF7Z4StxEpOz7BGd92rZn1VoBKioWavLNmyRvBgxF5oD05gS
Xi7FWVZZw3OW7qQAiE4Xb5Y6WqbyIX+CF426hL5+Nz3KHvTfg3IWOiOeuqn0
26HaHkqJDLpuFRVPqSBXewpi6qgD78mkTbbiK5tbmXw++zNJkHdNxsm1QVL6
ACpXFEzWyHWm6Nx1jlKzHKikfxVwDRvD0+N6q7sXHHLvdITzADnZ9z8XUZFm
5YCaWzMS1nXoePRF90x2pkLL7qjgwA38jmI3ILSdWgIxa5oLQ909n0jzbl5L
PAECfQlqab8F4WZ91PxEpjPuyPIuLb3em39or+dMVP2q0iu68BbwmB4bOXlr
G9a7js5IowS013YZO7IZa+4Ya9zrpY96O7efPlF0q
-----------end_max5_patcher-----------
</code></pre>

so I'm reopening the issue
