### ISSUE TITLE
Score v1.0.0b41 (windows) crashes on startup

### ISSUE THREAD

**Issue by tohox** [ossia/score#734]
Running Win10 Pro 64 (quad Xeon 3.5, 16GB, with nVidia Quadro FX4600). Score crashes soon after splash screen appears.

Is there a crash report saved somewhere?

Thanks,

**Comment by avilleret** [comment]
which version of Jack are you running ?
could you try to start it from a cmd prompt ? and send here the message that appear in the console ?

**Comment by tohox** [comment]
Didn't realize Jack was required as the last time I installed Score it ran out of the box.

Will install it and report back.

Thanks,

**Comment by tohox** [comment]
Installed Jack 1.9.11 64bits on a different computer with the same result. Score still crashes right after the  splash screen appears. Should I simply install Jack for Windows or are some additional run time libraries or path arguments required for Score to run?

When started from CLI no additional information is displayed.

Don't know if this has any incidence on the problem but both computers use the French Canadian locale.

Thanks,

**Comment by tohox** [comment]
Installing 1.0.0b40 on the same Windows machines works out of the box.

**Comment by bltzr** [comment]
> Installing 1.0.0b40 on the same Windows machines works out of the box.

yes, that's because *a lot* (and I mean a lot) has changed under the hood between v1b40 and v1b41, which should thus (and will) be renamed  v2a1

**Comment by avilleret** [comment]
Score v2a1 (aka 1.0.0b41) introduce audio support, hence Jack should be started *before* score.
If not, it crashes.
This is a kwon limitation (reported on the release note), in the future, I hope there will be a dialog to ask to start jack when launching Score (like the one Ardour provide at startup).
Let us know if it works after starting jack.

**Comment by jcelerier** [comment]
> This is a kwon limitation (reported on the release note), in the future, I hope there will be a dialog to ask to start jack when launching Score (like the one Ardour provide at startup).

it should be fixed in the latest commits though, it will now try to use portaudio instead if jack is not here

**Comment by tohox** [comment]
Understood. I installed Jack 1.9.11 and tried starting both JACK Audio Connection Kit and Jack PortAudio before starting Score v2a1 and it still crashes. I tried both 32bits and 64bits versions of Jack. Am not familiar with Jack so might not be starting the right component...

I don't need audio so I'll wait for the next release and use 1.0.0b40 in the meantime.

Thanks

**Comment by avilleret** [comment]
Hum... to fix your crash in the next release we need more details :-)
First of all, the component to use to start jack is QJackCtl, the name might not be exactly the same on Windows (I can't remember right now) but the interface looks the same :
![image](https://user-images.githubusercontent.com/504914/39400281-d30d12d2-4b2d-11e8-99eb-d9c6407afe62.png)
Once you've got this, try to start the audio server by pressing green arrow.
I really doubt that will works on the first try :-) but it's worth a try.
If it doesn't, open the preference panel and choose your driver/soundcard according to your setup.
You don't need special hardware, I setup an old Gigabyte Brix 2 weeks ago with Score.
If Jack fails to start, then Score will fails too.
So jack is the really first step to use Score >= 2.0.0

**Comment by jcelerier** [comment]
@tohox if you have the time, the latest release shouldn't require jack anymore (this was a bug) : https://github.com/OSSIA/score/releases ; if it still crashes it's certainly something else... I'll try in a clean virtual machine.

**Comment by tohox** [comment]
@avilleret This is what I did the first time around. Started the JackAudioConnection Kit and started the server which did so without complaining with the default parameters. Then I tried starting Score 2 both from the desktop shortcut and from the cli. Is there any kind of argument I can add to get debug info?
@jcelerier Just tried release 2.0.0-a3 with the same result (both with and without Jack running).

**Comment by tohox** [comment]
Hi, a quick followup. I just tried build 2.0.0-a3 on a third Windows 10 computer and it also crashed on startup.

**Comment by jcelerier** [comment]
hi! could you try a4 if you have a spare moment ? If it still does not work, I'm at loss :|

**Comment by tohox** [comment]
@jcelerier  YESSSSsss!
Thanks! :)
