### ISSUE TITLE
linker error on Ubuntu 18.04

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#831]
on commit cb4dc3b 
ld returns an error uppon linking "Integration_SerializationTest"

```
[ 27%] Linking CXX executable Integration_SerializationTest
/usr/bin/x86_64-linux-gnu-ld : option « --gdb-index » non reconnue
/usr/bin/x86_64-linux-gnu-ld : utiliser --help pour afficher l'aide-mémoire
collect2: error: ld returned 1 exit status
Tests/Integration/CMakeFiles/Integration_SerializationTest.dir/build.make:117: recipe for target 'Tests/Integration/Integration_SerializationTest' failed
CMakeFiles/Makefile2:2999: recipe for target 'Tests/Integration/CMakeFiles/Integration_SerializationTest.dir/all' failed
make[2]: *** [Tests/Integration/Integration_SerializationTest] Error 1
make[1]: *** [Tests/Integration/CMakeFiles/Integration_SerializationTest.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
```

even with INTEGRATION_TESTING set to OFF in the CMake, "Integration_SerializationTest" is always built, but fails to link

I manage to build score a couple days ago on the same config so i'll try to find the commit where this starts to occure

**Comment by thibaudk** [comment]
on commit  994e5f6 

with 
"-DSCORE_CONFIGURATION=static-release" 
added in the cmake cofiguration 
and 
make all_unity 
as suggested in 
https://github.com/OSSIA/score/wiki/Build-and-install/_compare/a4d6384%5E...a4d6384#diff-598d32d2d39f3fb1012d7270323a51f9L39  

the error now only occurs in the final stage of lincking and regards the "--threads" option 
```
[100%] Linking CXX executable ../../ossia-score
/usr/bin/x86_64-linux-gnu-ld : option « --threads » non reconnue
/usr/bin/x86_64-linux-gnu-ld : utiliser --help pour afficher l'aide-mémoire
```

**Comment by jcelerier** [comment]
should be fixed now

**Comment by thibaudk** [comment]
Yes all good!
Well done!
Thanks

**Comment by thibaudk** [comment]
the linker error is back since 
f748524 

weirdly, the branch that was merged in this commit builds fine
https://github.com/aliefhooghe/score

**Comment by jcelerier** [comment]
ah indeed, the submodule was to the wrong commit. @aliefhooghe <_<

**Comment by thibaudk** [comment]
Aah that was it.

Perfect!

Thanks!
